name: Update K8s Deployment
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubeconfig
      run: echo ${{ secrets.KUBECONFIG }} | base64 --decode > kubeconfig.yaml

    - name: Update deployment image
      run: kubectl --kubeconfig=kubeconfig.yaml set image deployment/my-deployment my-container=my-image:${{ github.sha }}

    - name: Verify deployment
      run: kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/my-deployment
