name: Build and push image to dockerhub 
on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12

    - name: docker version
      run: docker --version

    - name: Build image
      run: docker build -t nikhildobriyal/docker_images:v0.2.0 docker/
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Remote Repo
      run: docker push nikhildobriyal/docker_images:v0.2.0