name: Build and push image to dockerhub 
on: 
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Build image
      run: |
        IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-7)
        echo "Building image with tag: ${IMAGE_TAG}"
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${IMAGE_TAG} docker/

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image to DockerHub Repo
      run: |
        IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-7)
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${IMAGE_TAG}